# Generated by Django 2.2.24 on 2021-07-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=20)),
                ('lname', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(default='01-01-1990')),
                ('gender', models.CharField(default='M', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='LIB', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.CharField(default='LIB', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='published_in',
            field=models.DateField(default='01-01-1990'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='AVL', max_length=3),
        ),
    ]
