# Generated by Django 2.2.24 on 2021-07-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20210725_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_in',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
