# Generated by Django 2.2.24 on 2021-07-25 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20210725_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2021, 7, 25, 16, 45, 21, 918584, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
