# Generated by Django 2.2.24 on 2021-07-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20210725_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
